### ISSUE TITLE
Migrate away from SailsJS

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1556]
SailsJS is creating more overhead than it is providing value.  Migration to Koa is in the dev branch. 

- [X] Log into open opportunities
- [X] Search opportunities
- [X] Search users
- [X] View my profile
- [X] Edit my profile
- [X] Share a profile
- [ ] Integration tests
- [x] Send emails
- [x] Assign badges based on activity
- [x] Filter logs for sensitive info #1596
- [ ] Update developer docs #1586 
- [ ] Review #1288 -- prior work simply updated to new SailsJS, though there were some unfinished work items that should be reviewed once this work is complete.  We should close that issue and open new issues for any specific work items that we still believe are needed.

**Comment by bmcorum** [comment]
I think we should replace SailsJS for [Koa](http://koajs.com) (designed by the team behind Express). This is a lightweight framework with no middleware included in the core library. This will reduce overhead and bloat of the project since we would only install the middleware we intend to utilize.

**Comment by bmcorum** [comment]
Waterline ORM under the hood of SailsJS can be replaced with [postgres-gen](https://www.npmjs.com/package/postgres-gen) and [postgres-gen-dao](https://www.npmjs.com/package/postgres-gen-dao).

**Comment by bmcorum** [comment]
For better development debugging we can look at using [blue-ox](https://www.npmjs.com/package/blue-ox). For environment based configurations we can look at implementing the use of [flapjacks](https://www.npmjs.com/package/flapjacks)

**Comment by ultrasaurus** [comment]
I'm so glad you are looking into this!  I think the big question is about how to ensure that we can deliver a robust app during/after the transition.  One idea is to factor out the integration tests so they cover all the key use cases and are not directly using SailsJS in any way, then we can refactor the backend and ensure that we don't break existing functionality.

**Comment by LisaLNelson** [comment]
#1288 is related

**Comment by bmcorum** [comment]
- [ ]

**Comment by bmcorum** [comment]
- [X] Log into open opportunities
- [X] Search opportunities
- [X] Search users
- [X] View my profile
- [X] Edit my profile
- [X] Share a profile
- [ ] Send emails
- [ ] Assign badges based on activity

**Comment by ultrasaurus** [comment]
FYI -- moved checklist to the issue description -- now includes developer docs, and then we can add more items there, as needed
